version: '3.4'

services:
  chorus2api:
    image: deanxv/chorus2api:latest
    container_name: chorus2api
    restart: always
    ports:
      - "10011:10011"
    volumes:
      - ./data:/app/chorus2api/data
    environment:
      - CU_COOKIE=******  # cookie (多个请以,分隔)
      - API_SECRET=123456  # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔)
      - TZ=Asia/Shanghai